- name: install ansible PPA
  apt_repository: repo="ppa:ansible/ansible" state=present
  become: true
  
- name: reload apt cache
  apt: update_cache=true
  become: true

- name: install ansible on guest
  apt: name=ansible state=present
  become: true