- name: update apt cache
  apt: update_cache=true
  become: true

- name: make sure https is enabled for apt
  apt: name={{ item }} state=present
  with_items:
    - apt-transport-https
    - ca-certificates
  become: true

- name: install software-properties-common
  apt: name=software-properties-common state=present
  become: true
  